[colors.bright]
black = "#2b3745"
blue = "#e8b15f"
cyan = "#50adb5"
green = "#279f9d"
magenta = "#f16a64"
red = "#fd2e5a"
white = "#fafafa"
yellow = "#e8b15f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#2b3745"
blue = "#ffc36b"
cyan = "#5cc7d1"
green = "#2aacaa"
magenta = "#ff716b"
red = "#fe3762"
white = "#fafafa"
yellow = "#ffc36b"

[colors.primary]
background = "#0c1014"
#background = "#000000"
foreground = "#fafafa"

[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.normal]
family = "MesloLGS NF"
style = "Medium"

[scrolling]
history = 1000

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10
