#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &
polybar -r example &
xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d cmd code web
bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-0 -d 1 2 3

bspc config border_width        0
bspc config window_gap          8

#bspc config single_monocle false
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Alacritty desktop='term' follow=on
bspc rule -a Code desktop='code'
bspc rule -a qutebrowser desktop='web' follow=on
