#! /bin/sh

#xrandr --output Virtual1 --mode 2560x1440
#nitrogen --restore &
# source ~/.config/environment
~/.config/wallpapers/run.sh &

sudo VBoxService
VBoxClient-all
xbanish &

#sudo kmonad /etc/kmonad/gaming_kb_vb.kbd &
pgrep -x sxhkd >/dev/null || sxhkd &
#picom &
~/.config/picom/run.sh &
polybar -r center &
#polybar -r left &
#polybar -r right &
xsetroot -cursor_name left_ptr &
/usr/lib/xfce-polkit/xfce-polkit &

telegram-desktop &
kbdd &

bspc monitor Virtual1 -d   󰖟 1 2 3
#bspc monitor HDMI-0 -d  󰨞 󰖟 1 2 3
#bspc monitor DVI-D-0 -d 4 5 6
#bspc monitor DVI-I-1 -d  8 9

bspc config border_width 0
bspc config window_gap 8

bspc config automatic_scheme spiral

#bspc config single_monocle false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Alacritty # desktop='' follow=on
bspc rule -a Code desktop=''
bspc rule -a Neovim desktop='' follow=on
bspc rule -a qutebrowser desktop='󰖟' follow=on
bspc rule -a Yandex-browser desktop='󰖟' follow=on
bspc rule -a TelegramDesktop desktop='1'

bspc rule -a 'VirtualBox Manager' desktop='' follow=on
