-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- require("config.codeium")
-- require("lazy").setup({
--   extras = {
--     codeium = {
--       opts = function(_, opts)
--         table.insert(opts.sources, { name = "codeium", group_index = 1, priority = 1 })
--       end,
--     },
--   },
-- })
